
unidev:
    # Captcha
    captcha:
        default: none
        recaptcha:
            driver: recaptcha
            key: ~
            secret: ~
            type: checkbox
        image:
            driver: gregwar
            session_key: captcha_content
            lifetime: 300
            quality: 90
        none:
            driver: none
    # Image
    image:
        storage: local
        resize:
            enabled: true
            width: 1200
            height: 1200
            crop: false
            quality: 85
    amazon:
        key:
        secret:
        bucket:
        subfolder:
        endpoint:
        region:
    imgur:
        key:
        secret:
        album:
    local:
        path: asset/upload
