
unidev:
    image:
        storage: local
        resize:
            enabled: true
            width: 1200
            height: 1200
            crop: false
            quality: 85
    amazon:
        key:
        secret:
        bucket:
        subfolder:
        endpoint:
        region:
    imgur:
        key:
        secret:
        album:
    local:
        path: asset/upload
